### ISSUE TITLE
Can't make it work other than in app module

### ISSUE THREAD

**Issue by mtabaj** [denniske/ngx-translate-multi-http-loader#20] opened 2022-10-27 07:51 UTC
I use the new release 9.0, it works perfectly in my app module 

```
export function HttpLoaderFactory(httpBackend: HttpBackend) {
  return new MultiTranslateHttpLoader(httpBackend,
    ['/assets/i18n/core/']);
}
```

and

```
TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpBackend]
      }
    })
```

but when declare in another module

```
TranslateModule.forChild({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpBackend]
      }
    }),
```
It doesn't work.

**Comment by EricSch** [comment] 2022-10-27 18:57
Just an idea: Did you try with` TranslateModule.forChild();` I think you need the loader only once.

**Comment by rbalet** [comment] 2022-10-28 15:31
@mtabaj   
FYI, if you declare the `TranslateModule` in your `app.module.ts` file, then no need to import it again.

But maybe you need to import it in a child, but I do not understand the use case of it.  
Could you explain the reason why you would like to do it ?

Also, please provide the error message you get :)

**Comment by mtabaj** [comment] 2022-10-29 10:56
Hi @rbalet,

 

Thanks a lot for taking care.

I have a website with +20 pages / functionalities, in 3 languages, that are lazy loaded.

Each page has its languages files, which are maintained separately.

I don’t want all the json files to be loaded at the start of the app, I want that each module reads its language files when it is calle

 

De : Raphaël Balet ***@***.***> 
Envoyé : vendredi 28 octobre 2022 17:32
À : rbalet/ngx-translate-multi-http-loader ***@***.***>
Cc : Marcos Tabaj ***@***.***>; Mention ***@***.***>
Objet : Re: [rbalet/ngx-translate-multi-http-loader] Can't make it work other than in app module (Issue #20)

 

@mtabaj <https://github.com/mtabaj> 
FYI, if you declare the TranslateModule in your app.module.ts file, then no need to import it again.

But maybe you need to import it in a child, but I do not understand the use case of it.
Could you explain the reason why you would like to do it ?

**Comment by rbalet** [comment] 2022-10-30 19:05
@mtabaj OK thx, but still not sure why you will use this library for that matter.

I've prepared a [stackblitz](https://stackblitz.com/edit/ngx-translate-multi-http-loader-sample-2clau3?file=src%2Fapp%2Fapp.module.ts) project. 

Please copy this one and reproduce what you're doing in a fork of it.  
Then add it back here that I can see what you're trying to achieve.

That say, your problem seems not to be related to this project but to the [ngx-transalte](https://github.com/ngx-translate/core) one.  Or am I wrong?

**Comment by mtabaj** [comment] 2022-10-31 00:31
Hi Raphaël,

 

Thanks a lot for your help.

 

I forked and modify your project:

 

https://stackblitz.com/edit/ngx-translate-multi-http-loader-sample-vgqffd?file=src/app/home/home.component.ts

 

Maybe you’re right and the problem is with ngx-translate.  Please take a look.

 

Thanks again,

Marcos

 

 

De : Raphaël Balet ***@***.***> 
Envoyé : dimanche 30 octobre 2022 20:05
À : rbalet/ngx-translate-multi-http-loader ***@***.***>
Cc : Marcos Tabaj ***@***.***>; Mention ***@***.***>
Objet : Re: [rbalet/ngx-translate-multi-http-loader] Can't make it work other than in app module (Issue #20)

 

@mtabaj <https://github.com/mtabaj>  OK thx, but still not sure why you will use this library for that matter.

I've prepared a stackblitz <https://stackblitz.com/edit/ngx-translate-multi-http-loader-sample-2clau3?file=src%2Fapp%2Fapp.module.ts>  project.

Please copy this one and reproduce what you're doing in a fork of it.
Then add it back here that I can see what you're trying to achieve.

That say, your problem seems not to be related to this project but to the ngx-transalte <https://github.com/ngx-translate/core>  one. Or am I wrong?

**Comment by rbalet** [comment] 2022-10-31 09:20
@mtabaj Hi there.

Well, what you're doing is kinda incorrect and not optimized.

1. The example you show me doesn't have any error, so it seems to work the way it should.
2. You're loading twice the `/core` one in the `app.module` and then in the `home.module`. (Bad optimization).

So here is how you should do it.

1. Load the `core` in the app.module`
2. load with TranslateModule.forChild()` in the page you're lazy loading (Here the `home` one)
3. Do not use this library, since this isn't meant for that purpose (And this isn't optimized well enough for what you're doing).

so, in every page you'll be loading the page specific translation file, but in the core you'll load what every page needs.

I'm closing this issue, since I see no error here, please fill free to text me back in case this is not.

Have a nice day

**Closed as completed by rbalet** 2022-10-31 09:20 UTC
